config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :supplements do
    resources :reviews, only: [:new, :create, :edit, :update]
  end
  resources :reviews, only: [:destroy]
  resources :notifications
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :supplement

  def blank_stars
    5 - rating.to_i
  end
end

app/models/supplement.rb
class Supplement < ApplicationRecord
  belongs_to :user

  has_many :reviews
  has_many_attached :images

  validates :user, presence: true
  validates :name, presence: { message: "must be given please" }
  validates :quantity, presence: { message: "must be given please" }
  validates :frequency, presence: { message: "must be given please" }
  validates :images, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  geocoded_by :address
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :supplements, dependent: :destroy
  has_many :reviews
  has_many :notifications, as: :recipient, dependent: :destroy

  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    user = current_user
    @notifications = user.notifications
  end

  def create
    comment = params[:notification][:params]
    if CommentNotification.with(comment: comment).deliver(current_user)
      redirect_to notifications_path
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @users = User.all
    # The `geocoded` scope filters only users with coordinates
    @markers = @users.geocoded.map do |user| {
        lat: user.latitude,
        lng: user.longitude
      }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy]

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.supplement_id = params[:supplement_id]
    if @review.save!
      redirect_to supplements_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @supplement = Supplement.find(params[:supplement_id])
  end

  def update
    if @review.update(review_params)
      redirect_to supplements_path
    end
  end

  def destroy
    @review.destroy
    redirect_to supplements_path, status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_article
    @review = Review.find(params[:id])
  end
end

app/controllers/supplements_controller.rb
class SupplementsController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @supplements = Supplement.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @supplements = current_user.supplements
    end
  end

  def new
    @supplement = Supplement.new
  end

  def create
    @supplement = Supplement.new(supplement_params)
    @supplement.user = current_user
    if @supplement.save!
      comment = if @supplement.quantity == 1
                  "Don't forget to take #{@supplement.name} once #{@supplement.frequency}"
                else
                  "Don't forget to take #{@supplement.name} #{@supplement.quantity} times #{@supplement.frequency}"
                end
      CommentNotification.with(comment:).deliver(current_user)
      redirect_to supplements_path(@supplement)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @review = Review.new
    @notification = Notification.new
    # require "open-uri"
    # require "nokogiri"

    # url = "https://examine.com/supplements/#{@supplement}/"

    # html_file = URI.open(url).read
    # html_doc = Nokogiri::HTML.parse(html_file)

    # @description = html_doc.search('.leading-7 p').each { |description| description.text.strip }
  end

  def edit
  end

  def update
    if @supplement.update(supplement_params)
      redirect_to supplements_path(@supplement)
    end
  end

  def destroy
    @supplement.destroy
    redirect_to supplements_path(@supplement), status: :see_other
  end

  private

  def supplement_params
    params.require(:supplement).permit(:name, :price, :description, :quantity, :frequency, :remaining, :category, images: [])
  end

  def set_article
    @supplement = Supplement.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <title>My Daily Dose - keeping track of all your Supplements and Meds</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>

    <link href='https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.12.0/mapbox-gl.js'></script>

     <script src="https://kit.fontawesome.com/ae1402068d.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="app">
      <%= render 'shared/navbar' %>
      <main>
        <%= yield %>
      </main>
      <%= render 'shared/footer' %>
      <%= render "shared/flashes" %>
    </div>
  </body>

app/views/notifications/index.html.erb
<div class="container">
  <div class="card-product">
    <div class="d-flex features-icons-icon icons-big">
      <i class="fa-solid fa-list m-auto text-primary text-h1"></i>
    </div>
    <div class="card-product-infos">
      <h2>My Reminders</h2>
      <p>All of my current <strong>notifications</strong> are listed here.</p>
    </div>
  </div>
</div>

<div class="container-md p-4 py-xl-5">
  <div class="row gy-4 row-cols-1 row-cols-md-1 row-cols-xl-1">
    <% @notifications.each do |notification| %>
      <div class="card-supp g-4">
        <div class="card-supp-infos">
          <p><%= notification.params[:comment] %></p>
          <i class="fa-regular fa-bell bell-icon"></i>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "shared/banner" %>

<section class="section text-center features-icons">
  <div class="container">
    <div class="row">

      <div class="col-lg-4">
        <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
          <div class="d-flex features-icons-icon icons-big">
            <i class="fa-solid fa-pills m-auto text-primary text-h1"></i>
          </div>
          <h3>Step 1</h3>
          <p class="lead mb-0">Add your first supplement</p>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
          <div class="d-flex features-icons-icon icons-big">
            <i class="fa-solid fa-list m-auto text-primary text-h1"></i>
          </div>
          <h3>Step 2</h3>
          <p class="lead mb-0">Add relevant information and a reminder</p>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
          <div class="d-flex features-icons-icon icons-big">
            <i class="fa-regular fa-calendar-minus m-auto text-primary text-h1"></i>
          </div>
          <h3>Step 3</h3>
          <p class="lead mb-0">Get a notification when it's time to take your supplement</p>
        </div>
      </div>
    </div>
  </div>

  <%= render "shared/showcase" %>

  <!-- <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div> -->


  <div id='map' style='width: 100%; height: 300px;' data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <!--<script>
  mapboxgl.accessToken = "<%= ENV['MAPBOX_API_KEY'] %>";
  const map = new mapboxgl.Map({
      container: 'map', // container ID
      style: 'mapbox://styles/mapbox/streets-v12', // style URL
      center: [-74.5, 40], // starting position [lng, lat]
      zoom: 9, // starting zoom
  });
  </script> -->
</section>

app/views/reviews/edit.html.erb
<div class='container'>
  <h1>Editing page for Reviews</h1>
  <%= simple_form_for [@supplement, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Edit Review", class: "btn btn-primary", :style => "margin-bottom: 25px; margin-top: 10px; font-size: 20px;" %>
  <% end %>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <section>
    <div class="main-section">
      <div class="main-text text-center">
        <h1 class="display-1 text-center" >My supplements all in one place!</h1>
        <p class="text text-center" >The nice and simple way<br/>to track your supplements and get reminded just in time</p>
        <div class="container">
          <% if user_signed_in? == false %>
            <div class="row gy-2">
              <div class="col-12 col-md-12 offset-0" action="/app/views/devise/registrations/new.html.erb" method="get">
                <input class="bg-light shadow-lg form-control-lg landing-page-input" type="email" name="email" placeholder="Enter your email..."/>
              </div>
              <div class="col-md-12">
                <br><%= link_to "Sign up!", new_user_registration_path, class: "btn btn-primary" %>
              </div>
            </div>
          <% else %>
            <div class="col-md-12">
              <%= render "shared/searchbar" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/shared/_card.html.erb
<div class="container-md p-4 py-xl-5">
  <div class="row g-10 row-cols-2 row-cols-md-3 row-cols-xl-4">
    <% @supplements.each do |supplement| %>
      <%= link_to supplement_path(supplement) do %>
      <div class="card-supp col p-4">
        <%= cl_image_tag supplement.images[0].key, :cloud_name => "dach7c7ct", class: "img", width: 150 %>
        <div class="card-supp-infos p-3">
          <div>
            <h3><%= supplement.name %></h3>
            <% average = 0 %>
            <% supplement.reviews.each do |review| %>
              <% average += review.rating %>
            <% end %>
            <p><%= supplement.reviews.count > 0 ? (average.to_f / supplement.reviews.count).round(1) : nil %></p>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div class="carousel-window">
  <div id="carousel-1" class="carousel carousel-dark slide" data-bs-ride="false">
    <ol class="carousel-indicators">
      <li class="active" data-bs-target="#carousel-1" data-bs-slide-to="0"></li>
      <li data-bs-target="#carousel-1" data-bs-slide-to="1"></li>
      <li data-bs-target="#carousel-1" data-bs-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <% @supplement.images.each_with_index do |image, index| %>
        <div class="carousel-item <% if index == 0 %> active <% end %>" >
          <%= cl_image_tag image.key, :cloud_name => "dach7c7ct", height: 300 %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carousel-1" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-1" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon"></span>
      <span class="visually-hidden">Next</span>
    </a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center shadow-sm py-4" style="/*font-family: Poppins, sans-serif;*/">
  <div class="container">
    <div class="row row-cols-1 row-cols-lg-3">
      <div class="col">
        <p class="text-muted my-2">2022 My Daily Dose</p>
      </div>

      <div class="col">
          <ul class="list-inline my-2" style="color: var(--bs-primary);">
            <li class="list-inline-item me-4">
              <div class="bs-icon-circle bs-icon-primary bs-icon">
                <i class="fa-brands fa-facebook"></i>
              </div>
            </li>

            <li class="list-inline-item me-4">
              <div class="bs-icon-circle bs-icon-primary bs-icon">
                <i class="fa-brands fa-twitter"></i>
              </div>
            </li>

            <li class="list-inline-item">
              <div class="bs-icon-circle bs-icon-primary bs-icon">
                <i class="fa-brands fa-instagram"></i>
              </div>
            </li>
          </ul>
        </div>

        <div class="col">
          <ul class="list-inline my-2">
            <li class="list-inline-item"><a class="link-secondary" href="#">Privacy Policy</a></li>
            <li class="list-inline-item"><a class="link-secondary" href="#">Terms of Use</a></li>
          </ul>
        </div>
      </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dach7c7ct/image/upload/v1670472579/MyDailyDose_logo_428_194_px_ieeej8.png" %>
  <% end %>

  <ul class="navigation">
    <% if user_signed_in? %>
    <div id="index-links">
      <li class="nav-item">
        <%= link_to "My Supplements", supplements_path, class: "navbar-link-s" %>
      </li>
      <li>
        <%= link_to "My Reminders", notifications_path, class: "navbar-link-r" %>
      </li>
    </div>
    <li class="nav-item">
      <%= link_to "Add Supplement", new_supplement_path, class:"btn btn-primary" %>
    </li>
    <div id="navbarNavDropdown">
      <li class="nav-item dropdown">
        <%= image_tag "https://res.cloudinary.com/dach7c7ct/image/upload/v1669220890/Alex_avatar_ytczjp.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "My Supplements", supplements_path, class: "dropdown-item hidden" %>
          <%= link_to "My Reminders", notifications_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
        </div>
      </li>
    </div>
    <% else %>
      <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-primary" %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_reminder-card.html.erb
<div class="container">
  <% @notifications.each do |notification| %>
    <div class="card-product">
      <div class="d-flex features-icons-icon icons-big">
      <i class="fas fa-bell d-flex features-icons-icon icons-big"></i>
      </div>
      <div class="card-product-infos">
        <p><%= notification.params[:comment] %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_searchbar.html.erb
<%= form_with url: supplements_path, method: :get, class: "d-flex" do %>
  <div class='container search-container'>
    <%= text_field_tag :query,
      params[:query],
      class: "search-input",
      placeholder: "Find a supplement"
    %>
    <% end %>
    <%= submit_tag "Search", class: "btn search-btn" %>
  </div>

app/views/shared/_show-tabs.html.erb
<div class="conainer tabs">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="description-tab" data-bs-toggle="tab" data-bs-target="#description" type="button" role="tab" aria-controls="description" aria-selected="true">Description</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="instructions-tab" data-bs-toggle="tab" data-bs-target="#instructions" type="button" role="tab" aria-controls="instructions" aria-selected="false">Instructions</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="supply-tab" data-bs-toggle="tab" data-bs-target="#supply" type="button" role="tab" aria-controls="supply" aria-selected="false">Supply</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="reviews-tab" data-bs-toggle="tab" data-bs-target="#reviews" type="button" role="tab" aria-controls="reviews" aria-selected="true">Reviews</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="notifications-tab" data-bs-toggle="tab" data-bs-target="#notifications" type="button" role="tab" aria-controls="notifications" aria-selected="true">Notifications</button>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
        <br><h4 class="panel-title">What this supplement is good for:</h4><br>
        <p class="tab-content"><%= @supplement.description %></p>
      </div>
      <div class="tab-pane fade" id="instructions" role="tabpanel" aria-labelledby="instructions-tab">
        <br><h4 class="panel-title">How to take this supplement:</h4>
        <br><label for="frequency"><%= @supplement.quantity %> times:</label>
        <select id="frequency" name="frequency" class= "bg-light shadow-sm form-control-sm landing-page-input">
          <option value="daily">Daily</option>
          <option value="weekly">Weekly</option>
        </select>
        <select id="instructions" name="instructions" class= "bg-light shadow-sm form-control-sm landing-page-input">
          <option value="with-meal">with a meal</option>
          <option value="without-meal">before or after a meal</option>
          <option value="with-water">with a glass of water</option>
        </select>
      </div>
      <div class="tab-pane fade" id="supply" role="tabpanel" aria-labelledby="supply-tab">
        <br><h4 class="panel-title">How much you have left:</h4>
        <p><strong><%= @supplement.remaining %></strong> <%= @supplement.remaining == 1 ? 'pill left' : 'pills left' %></p>
      </div>
      <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
        <br><h3>Reviews</h3>
        <div>
          <% @supplement.reviews.each do |review| %>
            <%= review.content %><br>
            <% review.rating.times do %>
              <i class="fa-solid fa-star"></i>
            <% end %><br><br>
          <% end %>
        </div>
        <br><h3>Add a Review</h3>
        <div>
          <%= simple_form_for [@supplement, @review] do |f| %>
            <%= f.input :content %>
            <div class='form-div radio-inline'>
              <%= f.input :rating, as: :radio_buttons, collection: [1, 2, 3, 4, 5], :item_wrapper_class => 'inline' %>
            </div>
            <%= f.submit "Submit review", class: "btn btn-primary", :style => "margin-bottom: 25px; margin-top: 10px; font-size: 20px;" %>
          <% end %>
        </div>
      </div>
      <div class="tab-pane fade" id="notifications" role="tabpanel" aria-labelledby="notifications-tab">
        <br><h3>Notifications</h3>
        <div>

        </div>
        <div>
          <%= simple_form_for @notification do |f| %>
            <%= f.input :params, as: :json, label: 'Comment' %>
            <%= f.submit "Add notification", class: "btn btn-primary", :style => "margin-bottom: 25px; margin-top: 10px; font-size: 20px;" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_showcase.html.erb
<section class="container showcase">
    <div class="container-fluid p-0">
        <div class="row g-0">
            <div class="col-lg-6 text-white order-lg-2 showcase-img" style="background-image: url(healthy_life.png)"><span></span></div>
            <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                <h2>Your good reasons for taking supplements</h2>
                <p class="lead mb-0">With our growing understanding of the effectiveness of many dietary supplements there are more and more good reasons for taking them. Many have to take regular medication for chronic illnesses as well.</p>
            </div>
        </div>
        <div class="row g-0">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url(Patience.png);"><span></span></div>
            <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                <h2>It takes time to work</h2>
                <p class="lead mb-0">Of course, we know that you have to take your supplements consistently over a longer period of time to reap the benefits. If you run out you may lose your momentum.</p>
            </div>
        </div>
        <div class="row g-0">
            <div class="col-lg-6 text-white order-lg-2 showcase-img" style="background-image: url(Solution-MyDailyDose.png);"><span></span></div>
            <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                <h2>MyDailyDose helps you to stay consistent</h2>
                <p class="lead mb-0">With MyDailyDose you keep track of your supplements and we help you to reach your health goals. You know when to take them and when your supply runs low.</p>
            </div>
        </div>
    </div>
</section>
<section class="text-center bg-light testimonials">
    <div class="container">
        <h2 class="mb-5">The people behind MyDailyDose...</h2>
        <div class="row">
            <div class="col-lg-4">
                <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img class="rounded-circle img-fluid mb-3" src="David_M.jpeg" />
                    <h5>David M.</h5>
                    <p class="font-weight-light mb-0">&quot;The man for the visible side of things.&quot;</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img class="rounded-circle img-fluid mb-3" src="Alex_M.jpg" />
                    <h5>Alex M.</h5>
                    <p class="font-weight-light mb-0">&quot;The man for the invisible elements.&quot;</p>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img class="rounded-circle img-fluid mb-3" src="Dirk_M.jpg" />
                    <h5>Dirk M.</h5>
                    <p class="font-weight-light mb-0">&quot;The man for everything else.&quot;</p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/supplements/edit.html.erb
<%= link_to supplement_path(@supplement) do %>
  <i class="arrow fa-solid fa-circle-left"></i>
<% end %>

<div class='container form'>
  <h1>Enter changes for your supplement here:</h1>
  <%= simple_form_for @supplement do |f| %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :remaining %>
    <div class='form-div'>
      <%= f.input :quantity %>
      <%= f.input :frequency, as: :select, collection: ['Daily', 'Weekly', 'Monthly'], prompt: 'please select' %>
    </div>
    <%= f.input :category, as: :select, collection: ['vitamins', 'amino acids', 'minerals'] %>
    <%= f.input :images, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Edit Supplement", class: "btn btn-primary", :style => "margin-bottom: 25px; margin-top: 10px; font-size: 20px;" %>
  <% end %>
</div>

app/views/supplements/index.html.erb
<%= render "shared/searchbar" %>

<div class="container">
  <div class="card-product">
    <div class="d-flex features-icons-icon icons-big">
      <i class="fa-solid fa-list m-auto text-primary text-h1"></i>
    </div>
    <div class="card-product-infos">
      <h2>My Supplement Stack</h2>
      <p>All of my current <strong>supplements / medications</strong> are listed here.</p>
    </div>
  </div>
</div>

<%= render "shared/card" %>

app/views/supplements/new.html.erb
<%= link_to supplements_path do %>
  <i class="arrow fa-solid fa-circle-left"></i>
<% end %>

<div class="container form">

  <h2>Add Supplement to your Stack:</h2>

  <%= simple_form_for(@supplement) do |f| %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :remaining %>
    <div class='form-div'>
      <%= f.input :quantity %>
      <%= f.input :frequency, as: :select, collection: ['Daily', 'Weekly', 'Monthly'], prompt: 'Please select' %>
    </div>
    <%= f.input :category, as: :select, collection: ['vitamins', 'amino acids', 'minerals', 'dietary supplement', 'prescription medication'] %>
    <%= f.input :images, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Add supplement", :class => " btn btn-primary", :style => "margin-bottom: 25px; margin-top: 10px; font-size: 18px; width" %>
    <% if @supplement.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@supplement.errors.count, "error") %> prohibited this supplement from being saved:</h2>
        <ul>
          <% @supplement.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

app/views/supplements/show.html.erb
<%= link_to supplements_path do %>
  <i class="arrow fa-solid fa-circle-left"></i>
<% end %>
<div class="container">
  <%= render "shared/carousel" %>

  <div class="name-heading">
    <h3><%= @supplement.name %></h3>
    <%= link_to edit_supplement_path(@supplement) do %><i class="fa-solid fa-pen"></i> <% end %>
    <%= link_to supplement_path(@supplement), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
      <i class="fa-solid fa-trash"></i>
    <% end %>
  </div>

  <%= render "shared/show-tabs" %>
</div>